In [5]:
import numpy as np
import pandas as pd

# CSV'lerden verileri oku
points = np.array(pd.read_csv('points.csv'))
affects = np.array(pd.read_csv('affects.csv').iloc[0])  # 1=maximize, -1=minimize

def is_dominated(p, others, affects):
    """
    p: kontrol edilen nokta
    others: diğer noktalar (NxM)
    affects: feature etkileri (1 veya -1)
    """
    for other in others:
        # other tüm feature'larda p'den daha iyi mi?
        if np.all((other - p) * affects >= 0) and np.any((other - p) * affects > 0):
            return True
    return False

# Non-dominated noktaları bul
non_dominated = []
for i, p in enumerate(points):
    others = np.delete(points, i, axis=0)
    if not is_dominated(p, others, affects):
        non_dominated.append(p)

non_dominated = np.array(non_dominated)
print("Non-dominated points:")
print(non_dominated)


Non-dominated points:
[[5 2 7 1 9]
 [7 1 5 6 3]
 [6 3 8 2 5]
 [8 4 4 3 6]
 [9 5 9 7 1]]
